name: Build and Publish WorkflowEngine to Docker
on: [push]
  paths:
    - 'WorkflowEngine/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: pkalkman/mve-workflowengine
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./WorkflowEngine/Dockerfile
        context: ./WorkflowEngine/
        tags: "0.4.0"
