name: WorkflowEngine Build and Publish to Docker
on: 
  push:
    paths:
    - 'WorkflowEngine/**'
    - '.github/workflows/workflowengine.yml'
  schedule:
    - cron: '0 1 * * *'
jobs:
  version: 
    - name: Bump version
      uses: remorses/bump-version@js
      with:
        version_file: ./Workflowengine/VERSION
        prefix: WorkflowEngine
      env:
        GITHUB_TOKEN: {{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to pkalkman/mve-workflowengine on Docker Hub 
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: pkalkman/mve-workflowengine
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./WorkflowEngine/Dockerfile
        context: ./WorkflowEngine/
        tags: "0.4.6"


